import React, { useState } from 'react';
import { 
  Clock, 
  Activity, 
  CheckCircle2, 
  AlertTriangle, 
  RefreshCw, 
  Calendar as CalendarIcon, 
  Bell, 
  Zap, 
  Sparkles, 
  Plus, 
  ShieldCheck,
  Check,
  Volume2
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { CalendarEvent, AppNotification } from '../types';
import { parseDueDateToMs, isWithin24Hours } from '../services/deadlineRunner';
import { doc, setDoc, serverTimestamp } from 'firebase/firestore';
import { db } from '../firebase';
import { playDeadlineAlertChime } from '../utils/chimeSound';

interface BackgroundTaskRunnerWidgetProps {
  calendarEvents: CalendarEvent[];
  notifications: AppNotification[];
  isRunning: boolean;
  lastCheckTime: Date | null;
  checkCount: number;
  onManualCheck: () => Promise<void>;
}

export default function BackgroundTaskRunnerWidget({
  calendarEvents,
  notifications,
  isRunning,
  lastCheckTime,
  checkCount,
  onManualCheck
}: BackgroundTaskRunnerWidgetProps) {
  const [createdTestSuccess, setCreatedTestSuccess] = useState<string | null>(null);

  // Compute upcoming deadlines within 24 hours from current calendar events
  const nowMs = Date.now();
  const upcomingWithin24h = calendarEvents.filter(evt => {
    if (!evt.start) return false;
    const dueMs = parseDueDateToMs(evt.start);
    const { isWithin } = isWithin24Hours(dueMs, nowMs);
    return isWithin;
  });

  // Automated notifications generated by runner
  const automatedNotifications = notifications.filter(n => n.isAutomated || n.title.includes('Deadline'));

  // Quick helper to seed a sample 24-hour deadline in the 'calendar' collection to demonstrate runner
  const handleAddSample24hDeadline = async () => {
    try {
      // Set date to 18 hours from now
      const targetDate = new Date(Date.now() + 18 * 3600 * 1000);
      const dateStr = targetDate.toISOString().slice(0, 10);
      const sampleId = `evt-test-24h-${Date.now()}`;

      const sampleEvent: CalendarEvent = {
        id: sampleId,
        title: 'High-Priority Trailer Export & QC',
        start: dateStr,
        type: 'delivery',
        coupleName: 'Ananya & Sahil',
        color: '#EF4444'
      };

      await setDoc(doc(db, 'calendar', sampleId), {
        ...sampleEvent,
        createdAt: serverTimestamp()
      });

      setCreatedTestSuccess(`Created 24h deadline "${sampleEvent.title}" for ${dateStr}! Running background scan...`);
      playDeadlineAlertChime(0.3);
      await onManualCheck();

      setTimeout(() => {
        setCreatedTestSuccess(null);
      }, 5000);
    } catch (err) {
      console.error("Failed to create sample 24h deadline:", err);
    }
  };

  return (
    <div className="p-6 rounded-3xl glass-panel border border-gold-500/20 bg-gradient-to-br from-charcoal-900/90 via-luxury-green-950/20 to-charcoal-950 space-y-6 shadow-2xl relative overflow-hidden">
      
      {/* Decorative Glow background */}
      <div className="absolute -top-24 -right-24 w-60 h-60 bg-gold-500/10 rounded-full blur-3xl pointer-events-none" />

      {/* Widget Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-white/10 pb-5">
        <div className="flex items-center space-x-3.5">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-gold-500/20 to-amber-600/20 border border-gold-500/40 flex items-center justify-center text-gold-400 gold-glow shrink-0">
            <Zap className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-gold-400">
                Automated Service
              </span>
              <span className="flex items-center space-x-1 text-[9px] font-mono font-bold px-2 py-0.5 rounded-full bg-emerald-500/15 text-emerald-300 border border-emerald-500/30">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                <span>ACTIVE MONITOR</span>
              </span>
            </div>
            <h3 className="text-lg font-bold text-white font-display mt-0.5">
              Calendar Deadline Task Runner
            </h3>
            <p className="text-xs text-gray-400 font-mono mt-0.5">
              Scans 'calendar' collection & triggers automated alerts for tasks due within 24 hours.
            </p>
          </div>
        </div>

        {/* Action Controls */}
        <div className="flex flex-wrap items-center gap-2">
          <button
            type="button"
            onClick={() => playDeadlineAlertChime(0.35)}
            className="px-3.5 py-2 rounded-xl bg-charcoal-800 hover:bg-charcoal-700 text-amber-300 hover:text-amber-200 border border-amber-500/30 text-xs font-mono font-bold flex items-center space-x-1.5 cursor-pointer transition-all shadow-sm"
            title="Play the subtle premium chime notification sound"
          >
            <Volume2 className="w-3.5 h-3.5 text-amber-400" />
            <span>Test Chime</span>
          </button>

          <button
            type="button"
            onClick={handleAddSample24hDeadline}
            className="px-3.5 py-2 rounded-xl bg-charcoal-800 hover:bg-charcoal-700 text-gold-300 hover:text-gold-200 border border-gold-500/30 text-xs font-mono font-bold flex items-center space-x-1.5 cursor-pointer transition-all shadow-sm"
            title="Create a test deadline in 'calendar' collection due in 18h to test automation"
          >
            <Plus className="w-3.5 h-3.5" />
            <span>Test 24h Event</span>
          </button>

          <button
            type="button"
            onClick={() => onManualCheck()}
            disabled={isRunning}
            className="px-4 py-2 rounded-xl bg-gold-500 hover:bg-gold-400 text-charcoal-950 text-xs font-mono font-bold flex items-center space-x-2 cursor-pointer transition-all gold-glow disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${isRunning ? 'animate-spin' : ''}`} />
            <span>{isRunning ? 'Scanning...' : 'Run Check Now'}</span>
          </button>
        </div>
      </div>

      {/* Test Creation Banner */}
      <AnimatePresence>
        {createdTestSuccess && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="p-3 bg-emerald-500/15 border border-emerald-500/40 rounded-2xl text-emerald-300 text-xs font-mono flex items-center space-x-2"
          >
            <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
            <span>{createdTestSuccess}</span>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Metrics Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 font-mono text-xs">
        <div className="p-3.5 bg-charcoal-950/80 rounded-2xl border border-white/10 space-y-1">
          <span className="text-[10px] text-gray-400 uppercase font-bold flex items-center space-x-1">
            <CalendarIcon className="w-3 h-3 text-gold-400" />
            <span>Monitored Events</span>
          </span>
          <strong className="text-lg text-white font-bold block">
            {calendarEvents.length} Tasks
          </strong>
        </div>

        <div className="p-3.5 bg-charcoal-950/80 rounded-2xl border border-white/10 space-y-1">
          <span className="text-[10px] text-gray-400 uppercase font-bold flex items-center space-x-1">
            <Clock className="w-3 h-3 text-amber-400" />
            <span>Due Within 24h</span>
          </span>
          <strong className={`text-lg font-bold block ${upcomingWithin24h.length > 0 ? 'text-amber-400 animate-pulse' : 'text-gray-300'}`}>
            {upcomingWithin24h.length} Upcoming
          </strong>
        </div>

        <div className="p-3.5 bg-charcoal-950/80 rounded-2xl border border-white/10 space-y-1">
          <span className="text-[10px] text-gray-400 uppercase font-bold flex items-center space-x-1">
            <Bell className="w-3 h-3 text-emerald-400" />
            <span>Triggered Alerts</span>
          </span>
          <strong className="text-lg text-emerald-400 font-bold block">
            {automatedNotifications.length} Active
          </strong>
        </div>

        <div className="p-3.5 bg-charcoal-950/80 rounded-2xl border border-white/10 space-y-1">
          <span className="text-[10px] text-gray-400 uppercase font-bold flex items-center space-x-1">
            <Activity className="w-3 h-3 text-sky-400" />
            <span>Last Scan</span>
          </span>
          <strong className="text-xs text-sky-300 font-bold block truncate mt-1">
            {lastCheckTime ? lastCheckTime.toLocaleTimeString() : 'Just Now'} ({checkCount} scans)
          </strong>
        </div>
      </div>

      {/* List of Tasks / Events in Calendar within 24 Hours */}
      <div className="space-y-3 pt-1">
        <div className="flex items-center justify-between">
          <h4 className="text-xs font-mono font-bold uppercase text-gold-400 tracking-wider flex items-center space-x-1.5">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
            <span>Upcoming 'Calendar' Collection Deadlines (&lt; 24h)</span>
          </h4>
          <span className="text-[10px] font-mono text-gray-400">
            Auto-Trigger Status: <strong className="text-emerald-400">Enabled</strong>
          </span>
        </div>

        {upcomingWithin24h.length === 0 ? (
          <div className="p-4 bg-charcoal-950/60 rounded-2xl border border-white/5 text-center text-xs font-mono text-gray-400">
            ✨ No pending calendar deadlines within 24 hours. (Click <span className="text-gold-300 font-bold">"Test 24h Event"</span> above to create a test deadline and trigger the runner!)
          </div>
        ) : (
          <div className="space-y-2">
            {upcomingWithin24h.map((evt) => {
              const dueMs = parseDueDateToMs(evt.start);
              const { hoursRemaining } = isWithin24Hours(dueMs, nowMs);
              const isNotified = automatedNotifications.some(n => n.calendarEventId === evt.id || n.message.includes(evt.title));

              return (
                <div
                  key={evt.id}
                  className="p-3.5 bg-charcoal-950/90 rounded-2xl border border-amber-500/30 flex items-center justify-between space-x-3 text-xs font-mono"
                >
                  <div className="flex items-center space-x-3 min-w-0">
                    <span className="w-3 h-3 rounded-full shrink-0" style={{ backgroundColor: evt.color || '#EAB308' }} />
                    <div className="min-w-0">
                      <div className="font-bold text-white truncate">{evt.title}</div>
                      <div className="text-[10px] text-gray-400 truncate">
                        {evt.coupleName ? `Project: ${evt.coupleName} • ` : ''}Due: {evt.start}
                      </div>
                    </div>
                  </div>

                  <div className="flex items-center space-x-2 shrink-0">
                    <span className="px-2.5 py-1 rounded-lg bg-amber-500/20 text-amber-300 border border-amber-500/30 font-bold text-[10px]">
                      {hoursRemaining < 0 ? `Overdue ${Math.abs(Math.round(hoursRemaining))}h` : `~${Math.max(1, Math.round(hoursRemaining))}h left`}
                    </span>

                    {isNotified ? (
                      <span className="px-2 py-1 rounded-lg bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 text-[10px] font-bold flex items-center space-x-1">
                        <ShieldCheck className="w-3 h-3 text-emerald-400" />
                        <span className="hidden sm:inline">Alert Created</span>
                      </span>
                    ) : (
                      <button
                        type="button"
                        onClick={() => onManualCheck()}
                        className="px-2 py-1 rounded-lg bg-gold-500/20 hover:bg-gold-500/30 text-gold-300 border border-gold-500/30 text-[10px] font-bold cursor-pointer"
                      >
                        Trigger Alert
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

    </div>
  );
}
